server:
  port: 9003
spring:
  application:
    name: activemq-producer

  # springboot与activemq整合配置
  activemq:
    broker-url: tcp://127.0.0.1:61616 # 连接地址
    user: admin # activemq用户名
    password: admin  # activemq密码
    packages:
      trust-all: true # 配置信任 反序列化对象要用到的

  # 指定发送模式 （点对点 false ， 发布订阅 true）
  jms:
    pub-sub-domain: false
activemq:
  name: springboot-queue